### PR TITLE
new look + some book propositions for AI & Data science

### PR DESCRIPTION
**Pull request by XD-OB**
May Athena guide our way to salvation

### CODE REVIEW

**Comment by abellaismail7** [comment]
Yoooo this is great, can I ask for few changes.
 - the school of athens painting is so meaningful use it instead of the image of athena.
 - move the painting under Athena section so anyone can read description fisrt then see the image.
 If you can't give me permission to edit the files in this pr.
 thanks

**Comment by XD-OB** [comment]
Hey, ok I will do it, if you have the image send it to me

**Comment by abellaismail7** [comment]
https://upload.wikimedia.org/wikipedia/commons/4/49/%22The_School_of_Athens%22_by_Raffaello_Sanzio_da_Urbino.jpg

**Comment by XD-OB** [comment]
done  + added ayman suggested books

**Review by abellaismail7 — APPROVED** [review]

**Pull request merged**
